server:
	# 基础监听
	interface: 0.0.0.0
	interface: ::
	port: 5353
	do-ip4: yes
	do-ip6: no
	
	extended-statistics: yes
	statistics-cumulative: yes
	do-not-query-localhost: no
	
	# 缓存
	msg-cache-size: 512m
	rrset-cache-size: 1536m
	key-cache-size: 256m
	neg-cache-size: 128m
	infra-cache-numhosts: 50000

	cache-max-ttl: 86400
	cache-min-ttl: 600

	prefetch: yes
	prefetch-key: yes

	serve-expired: yes
	serve-expired-ttl: 259200
	serve-expired-ttl-reset: yes
	serve-expired-reply-ttl: 3
	serve-expired-client-timeout: 0
	
	# 性能
	num-threads: 1
	

	# DNSSEC
	auto-trust-anchor-file: "/var/lib/unbound/root.key"

	# RFC 8806 Local Root Zone
	root-hints: "/var/lib/unbound/root.hints"

remote-control:
	control-enable: yes
	control-use-cert: no
	control-interface: 127.0.0.1
	control-interface: ::1
