server:
# 基础监听
	interface: 0.0.0.0
	interface: ::
	port: 53
	
	# 缓存
	msg-cache-size: 256m
	rrset-cache-size: 512m

	cache-max-ttl: 86400
	cache-min-ttl: 60

	prefetch: yes
	prefetch-key: yes

	serve-expired: yes
	serve-expired-ttl: 86400
	serve-expired-client-timeout: 0
	
	# 性能
	num-threads: 4
	outgoing-range: 8192
	num-queries-per-thread: 4096
	so-reuseport: yes
	edns-buffer-size: 1232
	max-udp-size: 1232

	# DNSSEC
	auto-trust-anchor-file: "/var/lib/unbound/root.key"

	# RFC 8806 Local Root Zone
	root-hints: "/var/lib/unbound/root.hints"


