server:
# 基础监听
	interface: 0.0.0.0
	interface: ::
	port: 5353

	# 缓存
	msg-cache-size: 256m
	rrset-cache-size: 512m

	cache-max-ttl: 86400
	cache-min-ttl: 60

	prefetch: yes
	prefetch-key: yes

	serve-expired: yes
	serve-expired-ttl: 86400
	serve-expired-client-timeout: 1800
	
	# 性能
	num-threads: 4
	outgoing-range: 8192
	num-queries-per-thread: 4096
	so-reuseport: yes
	edns-buffer-size: 1232
	max-udp-size: 1232


	# 日志
	verbosity: 1
	##logfile: "/var/log/unbound/unbound.log"

	# 安全
	hide-identity: yes
	hide-version: yes

	harden-glue: yes
	harden-dnssec-stripped: yes
	harden-algo-downgrade: yes
	harden-short-bufsize: yes
	qname-minimisation: yes
	
	do-ip4: yes
	do-ip6: yes
	do-udp: yes
	do-tcp: yes
	
	tcp-upstream: yes
	max-udp-size: 3072

	# DNSSEC
	auto-trust-anchor-file: "/var/lib/unbound/root.key"

	# RFC 8806 Local Root Zone
	root-hints: "/var/lib/unbound/root.hints"
	
	auth-zone:
		name: "."
		zonefile: "/var/lib/unbound/root.zone"
		for-downstream: no
		for-upstream: yes
		fallback-enabled: yes
		url: "https://www.internic.net/domain/root.zone"

