name: Build Docker Image

on:
    workflow_dispatch:
    schedule:
        - cron: "0 15 * * *"
    push:
      branches:
        - main
      paths:
        - VERSION

permissions:
    contents: write

jobs:
    check:
        runs-on: ubuntu-latest
        outputs:
            changed: ${{ steps.check.outputs.changed }}
            version: ${{ steps.check.outputs.version }}

        steps:
            - uses: actions/checkout@v6
            - name: Get latest version
              id: latest
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                VERSION=$(gh release view \
                  --repo SvenShi/oxidns \
                  --json tagName \
                  -q .tagName)

                [ -n "$VERSION" ] || exit 1

                echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Compare version
              id: check
              run: |
                CURRENT=$(cat VERSION)
                LATEST="${{ steps.latest.outputs.version }}"

                if [ -z "$LATEST" ] || [ "$LATEST" = "null" ]; then
                  echo "::error::Invalid latest version"
                  exit 1
                fi

                if [ "$CURRENT" != "$LATEST" ]; then
                  echo "changed=true" >> $GITHUB_OUTPUT
                  echo "version=$LATEST" >> $GITHUB_OUTPUT
                else
                  echo "changed=false" >> $GITHUB_OUTPUT
                fi

            - name: Update VERSION file
              if: steps.check.outputs.changed == 'true'
              run: |
                echo "${{ steps.latest.outputs.version }}" > VERSION

            - name: Commit VERSION
              if: steps.check.outputs.changed == 'true'
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com

                git add VERSION
                git commit -m "Update OxiDNS version to ${{ steps.latest.outputs.version }}"
                git push

    build:
        needs: check
        if: needs.check.outputs.changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            
            - name: Update Zone Cache
              run: |
                curl -o ./files/root.hints https://www.internic.net/domain/named.cache
                
            - name: Login DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and Push
              uses: docker/build-push-action@v7
              with:
                context: .
                push: true
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/oxidns-server:latest
                    ${{ secrets.DOCKER_USERNAME }}/oxidns-server:${{ needs.check.outputs.version }}
